import { CONFIG } from './config';

interface UserInfo {
  displayName: string;
  username: string;
  orgId: string;
}

interface AuthTokens {
  accessToken: string;
  refreshToken: string;
  instanceUrl: string;
  loginUrl: string;
}

export function isAuthenticated(): boolean {
  return !!sessionStorage.getItem(CONFIG.STORAGE_KEYS.ACCESS_TOKEN);
}

export function getTokens(): AuthTokens | null {
  const accessToken = sessionStorage.getItem(CONFIG.STORAGE_KEYS.ACCESS_TOKEN);
  const refreshToken = sessionStorage.getItem(CONFIG.STORAGE_KEYS.REFRESH_TOKEN);
  const instanceUrl = sessionStorage.getItem(CONFIG.STORAGE_KEYS.INSTANCE_URL);
  const loginUrl = sessionStorage.getItem(CONFIG.STORAGE_KEYS.LOGIN_URL) || 'https://login.salesforce.com';

  if (!accessToken || !instanceUrl) return null;
  return { accessToken, refreshToken: refreshToken || '', instanceUrl, loginUrl };
}

export function getUserInfo(): UserInfo | null {
  const raw = sessionStorage.getItem(CONFIG.STORAGE_KEYS.USER_INFO);
  if (!raw) return null;
  try {
    return JSON.parse(raw);
  } catch {
    return null;
  }
}

export function storeAuth(tokens: AuthTokens, userInfo: UserInfo): void {
  sessionStorage.setItem(CONFIG.STORAGE_KEYS.ACCESS_TOKEN, tokens.accessToken);
  sessionStorage.setItem(CONFIG.STORAGE_KEYS.INSTANCE_URL, tokens.instanceUrl);
  sessionStorage.setItem(CONFIG.STORAGE_KEYS.LOGIN_URL, tokens.loginUrl);
  if (tokens.refreshToken) {
    sessionStorage.setItem(CONFIG.STORAGE_KEYS.REFRESH_TOKEN, tokens.refreshToken);
  }
  sessionStorage.setItem(CONFIG.STORAGE_KEYS.USER_INFO, JSON.stringify(userInfo));
}

/**
 * Updates just the access token (and optionally instance URL) after a refresh.
 * Preserves the refresh token and user info.
 */
export function updateAccessToken(accessToken: string, instanceUrl?: string): void {
  sessionStorage.setItem(CONFIG.STORAGE_KEYS.ACCESS_TOKEN, accessToken);
  if (instanceUrl) {
    sessionStorage.setItem(CONFIG.STORAGE_KEYS.INSTANCE_URL, instanceUrl);
  }
}

export function clearAuth(): void {
  Object.values(CONFIG.STORAGE_KEYS).forEach((key) => {
    sessionStorage.removeItem(key);
  });
}

export function initiateLogin(loginUrl: string = 'https://login.salesforce.com'): void {
  // Pass return_url so the Worker knows where to redirect after OAuth
  const returnUrl = window.location.href.split('#')[0]; // strip any existing hash

  // Generate a nonce that binds this OAuth round-trip to this tab.
  // The Worker echoes it back in the hash payload; handleHashCallback verifies
  // it before storing any tokens. Prevents an attacker from crafting a URL
  // that injects their own session into someone else's tab.
  const nonce = crypto.randomUUID();
  sessionStorage.setItem(CONFIG.STORAGE_KEYS.OAUTH_NONCE, nonce);

  const authUrl = `${CONFIG.BROKER_URL}/oauth/authorize?` + new URLSearchParams({
    login_url: loginUrl,
    return_url: returnUrl,
    nonce,
  }).toString();

  window.location.href = authUrl;
}

export function logout(): void {
  const tokens = getTokens();
  clearAuth();

  // Revoke token on Salesforce side via worker (best-effort)
  if (tokens?.accessToken) {
    fetch(`${CONFIG.BROKER_URL}/oauth/revoke`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ token: tokens.accessToken }),
    }).catch((err) => {
      console.warn('Token revocation failed (best-effort):', err);
    });
  }

  window.location.href = import.meta.env.BASE_URL;
}

/**
 * After OAuth, the Worker redirects back to the app with tokens encoded in the
 * URL hash: #sf_auth=<base64 JSON>
 *
 * We read and store them here, then clear the hash so tokens don't linger in
 * the browser history or get logged anywhere.
 *
 * Returns true if a valid auth payload was found and stored.
 */
export function handleHashCallback(): boolean {
  const hash = window.location.hash;
  if (!hash.startsWith('#sf_auth=')) return false;

  try {
    const encoded = hash.slice('#sf_auth='.length);
    const data = JSON.parse(atob(encoded));

    if (!data.access_token || !data.instance_url) return false;

    // Verify the nonce matches the one we stored when initiating login.
    // If it doesn't, this hash wasn't generated by a flow this tab started, refuse to store the tokens.
    const expectedNonce = sessionStorage.getItem(CONFIG.STORAGE_KEYS.OAUTH_NONCE);
    sessionStorage.removeItem(CONFIG.STORAGE_KEYS.OAUTH_NONCE);
    if (!expectedNonce || expectedNonce !== data.nonce) {
      window.history.replaceState(null, '', window.location.pathname + window.location.search);
      return false;
    }

    storeAuth(
      {
        accessToken: data.access_token,
        refreshToken: data.refresh_token || '',
        instanceUrl: data.instance_url,
        loginUrl: data.login_url || 'https://login.salesforce.com',
      },
      {
        displayName: data.display_name || 'User',
        username: data.username || '',
        orgId: data.org_id || '',
      }
    );

    // Clear hash from URL without triggering a page reload
    window.history.replaceState(null, '', window.location.pathname + window.location.search);
    return true;
  } catch {
    return false;
  }
}

/**
 * Calls the Worker's /oauth/refresh endpoint to exchange the stored refresh
 * token for a fresh access token. Returns the new access token on success,
 * or null if refresh failed (in which case the user needs to re-authenticate).
 *
 * De-duped: concurrent callers share a single in-flight refresh promise so
 * a deploy poll loop firing many 401s in a row only triggers one refresh.
 */
let refreshInFlight: Promise<string | null> | null = null;

export function refreshAccessToken(): Promise<string | null> {
  if (refreshInFlight) return refreshInFlight;

  refreshInFlight = (async () => {
    try {
      const tokens = getTokens();
      if (!tokens || !tokens.refreshToken) return null;

      const resp = await fetch(`${CONFIG.BROKER_URL}/oauth/refresh`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          refresh_token: tokens.refreshToken,
          login_url: tokens.loginUrl,
        }),
      });

      if (!resp.ok) return null;
      const data = await resp.json();
      if (!data.access_token) return null;

      updateAccessToken(data.access_token, data.instance_url);
      return data.access_token;
    } catch {
      return null;
    } finally {
      // Clear the in-flight promise on the next tick so concurrent callers
      // waiting on it still get this resolution, but later 401s start fresh.
      setTimeout(() => { refreshInFlight = null; }, 0);
    }
  })();

  return refreshInFlight;
}
